"""description field added to File model

Revision ID: 7e244aa3067e
Revises: fb28cd6377a2
Create Date: 2020-06-17 16:29:07.774194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e244aa3067e'
down_revision = 'fb28cd6377a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'description')
    # ### end Alembic commands ###
